# Simple Kubernetes deployment for personal website
# Two main parts: Deployment (runs the app) and Service (exposes it)

# Deployment: Runs your FastAPI app in pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website
spec:
  replicas: 2  # Run 2 copies of your app
  selector:
    matchLabels:
      app: personal-website
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      containers:
      - name: personal-website
        image: joshzacharytan/personal-website:latest
        ports:
        - containerPort: 8000  # Your FastAPI app runs on port 8000
        env:
        # Database connection - connects to MySQL on your host machine
        - name: MYSQL_HOST
          value: "host.docker.internal"
        - name: MYSQL_USER
          value: "mysql_username"      # Replace with your actual username
        - name: MYSQL_PASSWORD
          value: "mysql_password"  # Replace with your actual password
        - name: MYSQL_DB
          value: "mysql_db"   # Replace with your actual database name

---
# Service: Makes your app accessible from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: personal-website-service
spec:
  selector:
    app: personal-website
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080  # Access your app at localhost:30080
  type: NodePort

# How to use:
# 1. Replace the MYSQL_* values above with your actual database credentials
# 2. Deploy: kubectl apply -f k8s-deployment.yml
# 3. Check: kubectl get pods
# 4. Access: http://localhost:30080
# 5. Delete: kubectl delete -f k8s-deployment.yml